auth:
  twitter:
    api_key: OVVERRIDE_ME_IN_LOCAL_SETTINGS
    api_secret: OVVERRIDE_ME_IN_LOCAL_SETTINGS
  cloudinary:
    api_key: OVVERRIDE_ME_IN_LOCAL_SETTINGS
    api_secret: OVVERRIDE_ME_IN_LOCAL_SETTINGS
